name: Affiliate Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# Menambahkan opsi global agar semua runner menggunakan Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24 # Sekalian naikkan versi runtime Node.js project Anda ke versi 24 terbaru

      - run: npm install

      - run: npx playwright install chromium

      - run: node checker.js
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
